BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "cars" (
	"id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL,
	"price"	INTEGER NOT NULL,
	PRIMARY KEY("id")
);
INSERT INTO "cars" VALUES (1,'BMW',10000);
INSERT INTO "cars" VALUES (2,'AUDI',90000);
INSERT INTO "cars" VALUES (3,'SUDO',50000);
INSERT INTO "cars" VALUES (4,'LADA',44000);
COMMIT;
